export const CREATE_NEW_ACCOUNT_LOADING = "CREATE_NEW_ACCOUNT_LOADING";
export const CREATE_NEW_ACCOUNT_SUCCESS = "CREATE_NEW_ACCOUNT_SUCCESS";
export const CREATE_NEW_ACCOUNT_FAILD = "CREATE_NEW_ACCOUNT_FAILD";

export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILD = "LOGIN_USER_FAILD";

export const LOGOUT_USER = "LOGOUT_USER";
